### ISSUE TITLE
ReferenceError: proxy is not defined

### ISSUE THREAD

**Issue by h0ru5** [w3c/web-of-things-framework#2]
When trying to start ``node demo.js`` (after installing ws), an error is thrown referring to this line:

https://github.com/w3c/web-of-things-framework/blob/master/framework.js#L453
seems like the variable "proxy" is defined in a function scope

Node: v0.10.25 (latest on Ubuntu LTS)

Error Message:
```
started http server on port 8888
started web sockets server on port 8080

/.../web-of-things-framework/framework.js:453
exports.proxy = proxy;
                ^
ReferenceError: proxy is not defined
    at Object.<anonymous> (/.../web-of-things-framework/framework.js:453:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/.../web-of-things-framework/demo.js:1:73)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by Glavin001** [comment]
~~This could be it, `Proxy`: https://github.com/w3c/web-of-things-framework/blob/master/framework.js#L131~~

The exported `thing` is defined here: https://github.com/w3c/web-of-things-framework/blob/master/framework.js#L18-L49
And `create_proxy` is defined here in a similar way: https://github.com/w3c/web-of-things-framework/blob/master/framework.js#L127-L158
So maybe `exports.proxy = proxy;` should be `exports.proxy = create_proxy;`, if not rename `create_proxy` to simply `proxy`.

**Comment by draggett** [comment]
Fixed.

I had changed the function name and forgot to update the export statement. I’ve also commented out the call from init_dependencies as a temporary measure while I come up with a robust test of the URI for an external server and complete the coding involved in register_proxy.

> On 1 Jun 2015, at 15:09, Johannes Hund <notifications@github.com> wrote:
> 
> When trying to start node demo.js (after installing ws), an error is thrown referring to this line:
> 
> https://github.com/w3c/web-of-things-framework/blob/master/framework.js#L453 <https://github.com/w3c/web-of-things-framework/blob/master/framework.js#L453>
> seems like the variable "proxy" is defined in a function scope
> 
> Node: v0.10.25 (latest on Ubuntu LTS)
> 
> Error Message:
> 
> started http server on port 8888
> started web sockets server on port 8080
> 
> /.../web-of-things-framework/framework.js:453
> exports.proxy = proxy;
>                 ^
> ReferenceError: proxy is not defined
>     at Object.<anonymous> (/.../web-of-things-framework/framework.js:453:17)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/.../web-of-things-framework/demo.js:1:73)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
> —
> Reply to this email directly or view it on GitHub <https://github.com/w3c/web-of-things-framework/issues/2>.
> 

—
   Dave Raggett <dsr@w3.org <mailto:dsr@w3.org>>

**Comment by h0ru5** [comment]
I see, you meant to export the factory function. confirmed fixed.
