### ISSUE TITLE
Loop closures causing several types of bugs

### ISSUE THREAD

**Issue by bubbafat** [w3c/web-of-things-framework#29]
There is an issue that appears in several parts of the node server where improper loop closures are causing bugs.  For example if I define this thing model:

```javascript
wot.thing("twoprops", {
    "@properties": {
        "property1": "string",
        "property2": "string"
    }
}, {
    start: function(thing) {
        console.log("setting property 1");
        thing.property1 = "property 1";

        console.log("setting property 2");
        thing.property2 = "property 2";
    },
    stop: function(thing) {},
});
```

When start is called you would expect framework.js (or wot.js) to send the patch message for both property1 and property2 - however it does not.  It sends property2 twice.  I created a mocha test to reproduce this - the output is:

```
started http server on port 8888
started web sockets server on port 8080
creating: twoprops
registering http://localhost:8888/wot/twoprops
starting1 twoprops
setting property 1
setting twoprops.property2 = property 1
setting property 2
setting twoprops.property2 = property 2
```

Notice:

setting twoprops.property**2** = property **1**

The bug is the classic loop closure issue (described in many places - but [here is a good explanation](http://www.mennovanslooten.nl/blog/post/62))

The problem can be seen [here in framework.js](https://github.com/w3c/web-of-things-framework/blob/master/framework.js#L396) - the loop modifies the value of prop but also uses it in a closure.  So in the end all the defined properties use the same property - the last in the loop.

A fix is to wrap this in an anonymous function such as this:

```javascript
for (var prop in properties) {
    if (properties.hasOwnProperty(prop)) {
        thing._properties[prop] = null;

        (function(property) {
            Object.defineProperty(thing, property, {
                get: function () {
                    return thing._values[property];
                },
                        
                set: function (value) {
                    thing._values[property] = value;
                    var message = {
                        uri: thing._uri,
                        patch: property,
                        data: value
                    };
                            
                    ws.send(JSON.stringify(message));
                }
            });
        })(prop);
    }
}
```

This bug occurs in several parts of the code.  I have submitted a pull request that fixes them but it was reverted - I believe because of whitespace issues (please let me know if for some other reason).

I will submit another pull request referencing this issue.

**Comment by draggett** [comment]
Thanks for looking into this, much appreciated.  There was a lot of other changes, and I was concerned that what we were both doing might conflict. If you can submit a fresh update I will merge it in.

**Comment by bubbafat** [comment]
I've updated pull request #30 to include your latest changes and fixed additional issues (a typo that caused an undefined continuation instance to be used and a missing var decl pushing base_uri into global scope.

**Comment by bubbafat** [comment]
I believe this issue can be closed now.  Thanks for merging!
