### ISSUE TITLE
events.js:72         throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by smof** [w3c/web-of-things-framework#4]
Vanilla install.  Cloned repo, installed dependencies and upon node demo.js receive the following error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:448:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by mpetyx** [comment]
Could you elaborate more on this?
Did you install the ws dependency?
I also had a vanilla install this morning, open the project with the [Webstorm IDE](https://www.jetbrains.com/webstorm/) and from there I selected to run the demo.js file and it worked just fine.

**Comment by Glavin001** [comment]
> Error: listen EADDRINUSE

This occurs when the port is already in use.

If you have something else already running on port 8888 it will break. See https://github.com/w3c/web-of-things-framework/blob/885cf975bded37825d26f08703001c5a2a4b76fe/httpd.js#L5

I believe there was another port that is used. I'll look that up. One minute.

**Comment by smof** [comment]
It was port 8080 that was in use, not 8888. Thanks.
