### ISSUE TITLE
Add thing into http registry

### ISSUE THREAD

**Issue by simwar81** [w3c/web-of-things-framework#6]
Hello,
I think the line #33  of framework.js:

registry[uri] = { model: model, thing: this };

should be replaced by

registry[name] = { model: model, thing: this };

because "name" is the thing's id and http server search it into registry by id.

Regards
Simone Guerra

**Comment by draggett** [comment]
The code is in transition, and the registry will combine locally hosted things and proxies for remote things, so the idea is to use the URI as the key. I am behind on this as I have something like 200 volunteers to reply to via email.
