### ISSUE TITLE
Create a gitter.im channel to have a chat space

### ISSUE THREAD

**Issue by dgomesbr** [w3c/web-of-things-framework#9]
I'm currently using http://gitter.im within other repos to chat over issues, map specific work etc. @draggett could you please elaborate on that to see if would work with us?

**Comment by draggett** [comment]
> On 3 Jun 2015, at 14:45, Diego Magalhães <notifications@github.com> wrote:
> 
> I'm currently using http://gitter.im <http://gitter.im/> within other repos to chat over issues, map specific work etc. @draggett <https://github.com/draggett> could you please elaborate on that to see if would work with us?
> 

At W3C we generally use IRC, and host irc.w3.org <http://irc.w3.org/> which can also be used from a web browser.  Tell me more about the benefits of gitter?

—
   Dave Raggett <dsr@w3.org <mailto:dsr@w3.org>>

**Comment by mpetyx** [comment]
GItter is indeed a nice solution and it has also mobile and desktop apps.I've used irc.w3.org many times, but it is not that handy and it does not integrate that well with git.
Most recently in most collaborative projects we've switched to [Slack](https://slack.com/) which has integration to many many existing apps, it is totally free, it keeps history and most developers I would guess they already have it installed on their dev machines.
So, I am just saying now we have three alternatives:
* irc
* gitter
* slack

Having used extensively all of them, I would say that slack is handier..

**Comment by dgomesbr** [comment]
@mpetyx I agree, don't know how freemium of slack works, but it's even better than gitter.

**Comment by mpetyx** [comment]
Should we set up something in order to chat?
Anything...

**Comment by draggett** [comment]
> On 8 Jun 2015, at 11:21, Michael Petychakis <notifications@github.com> wrote:
> 
> Should we set up something in order to chat?
> Anything...
> 

I took the part of least resistance and added a Gitter button to the contrib section in ready.md

I see that gitter also supports markdown, which fits in well along with other features for integration with github.

—
   Dave Raggett <dsr@w3.org <mailto:dsr@w3.org>>
